// <auto-generated />
using ASP.NETCoreWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NETCoreWebApplication.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210119085819_Added column Color in WeeksType")]
    partial class AddedcolumnColorinWeeksType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Auditory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auditories");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.DaysWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DaysWeeks");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AuditoryId")
                        .HasColumnType("int");

                    b.Property<int>("DaysWeekId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimetableId")
                        .HasColumnType("int");

                    b.Property<int>("WeeksTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditoryId");

                    b.HasIndex("DaysWeekId");

                    b.HasIndex("TimetableId");

                    b.HasIndex("WeeksTypeId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.WeeksType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeeksTypes");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Lesson", b =>
                {
                    b.HasOne("ASP.NETCoreWebApplication.Models.Auditory", "Auditory")
                        .WithMany("Lessons")
                        .HasForeignKey("AuditoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCoreWebApplication.Models.DaysWeek", "DaysWeek")
                        .WithMany("Lessons")
                        .HasForeignKey("DaysWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCoreWebApplication.Models.Timetable", "Timetable")
                        .WithMany("Lessons")
                        .HasForeignKey("TimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCoreWebApplication.Models.WeeksType", "WeeksType")
                        .WithMany("Lessons")
                        .HasForeignKey("WeeksTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditory");

                    b.Navigation("DaysWeek");

                    b.Navigation("Timetable");

                    b.Navigation("WeeksType");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Auditory", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.DaysWeek", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Timetable", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.WeeksType", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
