// <auto-generated />
using System;
using ASP.NETCoreWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NETCoreWebApplication.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210121102258_Seeding initial data")]
    partial class Seedinginitialdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Auditory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auditories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "211А"
                        },
                        new
                        {
                            Id = 2,
                            Name = "212А"
                        },
                        new
                        {
                            Id = 3,
                            Name = "213А"
                        },
                        new
                        {
                            Id = 4,
                            Name = "214А"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.DaysWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DaysWeeks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Понедельник"
                        },
                        new
                        {
                            Id = 2,
                            Day = "Вторник"
                        },
                        new
                        {
                            Id = 3,
                            Day = "Среда"
                        },
                        new
                        {
                            Id = 4,
                            Day = "Четверг"
                        },
                        new
                        {
                            Id = 5,
                            Day = "Пятница"
                        },
                        new
                        {
                            Id = 6,
                            Day = "Суббота"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AuditoryId")
                        .HasColumnType("int");

                    b.Property<int>("DaysWeekId")
                        .HasColumnType("int");

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("TimetableId")
                        .HasColumnType("int");

                    b.Property<int>("WeeksTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditoryId");

                    b.HasIndex("DaysWeekId");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TimetableId");

                    b.HasIndex("WeeksTypeId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.LessonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LessonTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Лекция"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Практика"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DaysWeekId")
                        .HasColumnType("int");

                    b.Property<int?>("TimetableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DaysWeekId");

                    b.HasIndex("TimetableId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timetables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = "10:20",
                            StartTime = "9:00"
                        },
                        new
                        {
                            Id = 2,
                            EndTime = "11:50",
                            StartTime = "10:30"
                        },
                        new
                        {
                            Id = 3,
                            EndTime = "13:40",
                            StartTime = "12:20"
                        },
                        new
                        {
                            Id = 4,
                            EndTime = "15:10",
                            StartTime = "13:50"
                        },
                        new
                        {
                            Id = 5,
                            EndTime = "16:50",
                            StartTime = "15:30"
                        },
                        new
                        {
                            Id = 6,
                            EndTime = "18:20",
                            StartTime = "17:00"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.WeeksType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeeksTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#35cc5d",
                            Type = "Зеленая"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#ffffff",
                            Type = "Белая"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#080808",
                            Type = "Все"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Lesson", b =>
                {
                    b.HasOne("ASP.NETCoreWebApplication.Models.Auditory", "Auditory")
                        .WithMany("Lessons")
                        .HasForeignKey("AuditoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCoreWebApplication.Models.DaysWeek", "DaysWeek")
                        .WithMany("Lessons")
                        .HasForeignKey("DaysWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCoreWebApplication.Models.LessonType", "LessonType")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCoreWebApplication.Models.Schedule", "Schedule")
                        .WithMany("Lessons")
                        .HasForeignKey("ScheduleId");

                    b.HasOne("ASP.NETCoreWebApplication.Models.Timetable", "Timetable")
                        .WithMany("Lessons")
                        .HasForeignKey("TimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCoreWebApplication.Models.WeeksType", "WeeksType")
                        .WithMany("Lessons")
                        .HasForeignKey("WeeksTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditory");

                    b.Navigation("DaysWeek");

                    b.Navigation("LessonType");

                    b.Navigation("Schedule");

                    b.Navigation("Timetable");

                    b.Navigation("WeeksType");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Schedule", b =>
                {
                    b.HasOne("ASP.NETCoreWebApplication.Models.DaysWeek", "DaysWeek")
                        .WithMany()
                        .HasForeignKey("DaysWeekId");

                    b.HasOne("ASP.NETCoreWebApplication.Models.Timetable", "Timetable")
                        .WithMany()
                        .HasForeignKey("TimetableId");

                    b.Navigation("DaysWeek");

                    b.Navigation("Timetable");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Auditory", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.DaysWeek", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.LessonType", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Schedule", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.Timetable", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.WeeksType", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
